### PR TITLE
Addproject

### PR DESCRIPTION
**Pull request by karliatto**
issue #44 
- functionality to add projects with one bitcoin  token

### CODE REVIEW

**Comment by victorbrender** [comment]
The log file is not supposed to be included in the PR; it should be added to .gitignore instead.

**Comment by karliatto** [comment]
done! thank you for noticing this.

**Comment by karliatto** [comment]
Ok I got it, I created a testing database and testing environment just using 'process.env.TEST' in the config.js file,and it is working very well.  :) 
But I need to run a server in one terminal and then run 'npm test' in other terminal to make it work.

I think it can be done with grunt but I still don't know how

**Comment by karliatto** [comment]
I am closing this pull request and I am going to create two separates ones, one with add project functionality and the other with test environment.  it is going to be more clear, clean and beautifull

**Pull request closed without merging**
