### PR TITLE
User creating script (initial commit)

### PR DESCRIPTION
**Pull request by plurlatero**
Initial commit, no database usage yet

### CODE REVIEW

**Comment by pajasevi** [comment]
+1

**Comment by chill117** [comment]
Looks great so far. Should I wait for the database part?

**Comment by plurlatero** [comment]
Yes, better wait until the next one, I'll commit the update with db today or tomorrow. Now I know how pull requests are done ;)

**Comment by plurlatero** [comment]
Hi, I updated the create-user.js (now it creates mysql table and stores info there). Some improvements are to be done (e.g., check username uniqueness before asking all the fields), but it works now.

**Pull request merged**
